import baseMatcha from './assets/baseMatcha.jpg';
import iceMatcha from './assets/ice.jpg';
import tonic from './assets/tonic.jpg';
import coconut from './assets/coconutMatcha.png';
import blue from './assets/blue.png';
import lemonade from './assets/lemonade.png';
import ceremonial from './assets/ceremonial.png';
import premium from './assets/premium.png';
import baking from './assets/baking.png';
import organic from './assets/organic.png';
import blend from './assets/blend.png';
import powder from './assets/powder.png';



export const matchaReady = [
    {
        id: 'classic-hot',
        name: 'Classic Matcha',
        name_ru: 'Классическая матча',
        type: 'hot',
        description: 'Традиционно взбитая горячая матча без сахара.',
        ingredients: ['вода', 'порошок матча (ceremonial)'],
        size_ml: [180, 250],
        sweetness: ['unsweetened'],
        dairy_free: true,
        caffeine_mg_est: 70,
        tags: ['classic', 'minimal'],
        image: baseMatcha,
        price: { small: 390, large: 420 },
    },
    {
        id: 'iced-latte',
        name: 'Iced Matcha Latte',
        name_ru: 'Айсед матча-латте',
        type: 'cold',
        description: 'Освежающий латте с матча, молоко на выбор, лёд.',
        ingredients: ['матча', 'молоко', 'лёд', 'сироп по желанию'],
        size_ml: [300, 400],
        sweetness: ['unsweetened', 'light', 'regular'],
        dairy_free: false,
        caffeine_mg_est: 65,
        tags: ['latte', 'popular'],
        image: iceMatcha,
        price: { small: 420, large: 490 },
    },
    {
        id: 'blue-latte',
        name: 'Blue Matcha Latte',
        name_ru: 'Голубая матча-латте',
        type: 'hot',
        description: 'Нежный латте на голубой матче с мягким вкусом и природным цветом.',
        ingredients: ['голубая матча', 'молоко на выбор'],
        size_ml: [250, 350],
        sweetness: ['unsweetened', 'light'],
        dairy_free: true,
        caffeine_mg_est: 0,
        tags: ['latte', 'colorful'],
        image: blue,
        price: { small: 480, large: 540 },
    },
    {
        id: 'coconut-latte',
        name: 'Coconut Matcha',
        name_ru: 'Кокосовая матча',
        type: 'cold',
        description: 'Матча с кокосовым молоком и лёгкой сладостью.',
        ingredients: ['матча', 'кокосовое молоко', 'лёд', 'сироп кокос (по желанию)'],
        size_ml: [300, 400],
        sweetness: ['light', 'regular'],
        dairy_free: true,
        caffeine_mg_est: 60,
        tags: ['tropical', 'latte'],
        image: coconut,
        price: { small: 480, large: 540 },
    },
    {
        id: 'lemonade',
        name: 'Matcha Lemonade',
        name_ru: 'Матча-лимонад',
        type: 'cold',
        description: 'Игривое сочетание матчи, лимона и газировки/воды.',
        ingredients: ['матча', 'лимонный сок', 'вода или сода', 'лёд', 'сироп'],
        size_ml: [300, 450],
        sweetness: ['light', 'regular'],
        dairy_free: true,
        caffeine_mg_est: 55,
        tags: ['citrus', 'refreshing'],
        image: lemonade,
        price: { small: 440, large: 500 },
    },
    {
        id: 'tonic',
        name: 'Sparkling Matcha Tonic',
        name_ru: 'Искристая матча-тоник',
        type: 'cold',
        description: 'Матча на тонике с лёгкой горчинкой и пузырьками.',
        ingredients: ['матча', 'тоник', 'лёд', 'лайм'],
        size_ml: [300, 400],
        sweetness: ['unsweetened', 'light'],
        dairy_free: true,
        caffeine_mg_est: 55,
        tags: ['sparkling', 'signature'],
        image: tonic,
        price: { small: 490, large: 560 },
    },
];

export const matchaPowder = [
    {
        id: 'ceremonial',
        name: 'Ceremonial Matcha',
        name_ru: 'Церемониальная матча',
        grade: 'ceremonial',
        description: 'Высший сорт из молодых листьев тенча, ярко-зелёный цвет, мягкий сладковатый вкус. Подходит для традиционного взбивания в чаван.',
        origin: 'Япония, Удзи (Киото)',
        weight_g: [100, 600],
        caffeine_mg_per_serving: 70,
        packaging: 'зип-пакет',
        tags: ['premium', 'traditional', 'umami'],
        image: ceremonial,
        price: { '100 гр.': 650, '600 гр.': 1990 },
    },
    {
        id: 'premium-latte',
        name: 'Premium Latte Matcha',
        name_ru: 'Премиум для латте',
        grade: 'premium',
        description: 'Чистая матча яркого цвета, идеально растворяется в молоке, сбалансированная горчинка и сладость.',
        origin: 'Япония, Сидзуока',
        weight_g: [150, 500],
        caffeine_mg_per_serving: 65,
        packaging: 'зип-пакет',
        tags: ['latte', 'smooth'],
        image: premium,
        price: { '150 гр.': 890, '500 гр.': 1450 },
    },
    {
        id: 'culinary',
        name: 'Culinary Matcha',
        name_ru: 'Кулинарная матча',
        grade: 'culinary',
        description: 'Сорт для выпечки, десертов и смузи. Более выраженная горчинка, идеально подходит для рецептов.',
        origin: 'Япония, Нисио',
        weight_g: [100, 950],
        caffeine_mg_per_serving: 55,
        packaging: 'зип-пакет',
        tags: ['cooking', 'baking', 'smoothie'],
        image: baking,
        price: { '100 гр.': 1400, '950 гр.': 2850 },
    },
    {
        id: 'organic',
        name: 'Organic Matcha',
        name_ru: 'Органическая матча',
        grade: 'premium',
        description: 'Выращена без пестицидов, сертифицированная органическая матча. Чистый вкус, насыщенный зелёный цвет.',
        origin: 'Япония, Кагосима',
        weight_g: [50, 550],
        caffeine_mg_per_serving: 60,
        packaging: 'банка или зип-пакет',
        tags: ['organic', 'eco', 'natural'],
        image: organic,
        price: { '50 гр.': 850, '550 гр.': 3500 },
    },
    {
        id: 'blend',
        name: 'Matcha Blend',
        name_ru: 'Матча-бленд',
        grade: 'standard',
        description: 'Сбалансированная смесь церемониальной и кулинарной матчи для универсального использования.',
        origin: 'Япония, смесь регионов',
        weight_g: [100, 350],
        caffeine_mg_per_serving: 60,
        packaging: 'зип-пакет',
        tags: ['universal', 'versatile'],
        image: blend,
        price: { '100 гр.': 990, '350 гр.': 2550 },
    },
    {
        id: 'instant',
        name: 'Instant Matcha',
        name_ru: 'Растворимая матча',
        grade: 'instant',
        description: 'Удобная порошковая форма, быстро растворяется в воде. Подходит для офисов и быстрых напитков.',
        origin: 'Япония',
        weight_g: [50, 250],
        caffeine_mg_per_serving: 50,
        packaging: 'стик-пакеты или банка',
        tags: ['instant', 'easy', 'office'],
        image: powder,
        price: { '50 гр.': 350, '250 гр.': 1250 },
    },
];
